### ISSUE TITLE
pressure plate do not opens modern doors

### ISSUE THREAD

**Issue by mercadanteus** [MrCrayfish/MrCrayfishFurnitureMod#378]
Pressure plate do not opens modern doors anymore, using 12.2 version.

**Comment by fandomaniac** [comment]
I just noticed this today. It used to work and must have broken in one of the newer updates,

**Comment by Phoenix13uk** [comment]
dont open gates either

**Comment by Graywaren** [comment]
Would love to see this fixed.... such a bummer. I love the sliding doors!

**Comment by alexvance89** [comment]
Can confirm this is not working for me as well in 1.12.2 using 6.2.0

**Comment by UltiMaxCZ** [comment]
I fixed it by replacing sliding door files in 6.3.0 with files from 5.12.0 version.

[CFM 6.3.0 - MC 1.12.2 - Sliding Doors Fix.zip](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3436829/CFM.6.3.0.-.MC.1.12.2.-.Sliding.Doors.Fix.zip)

**Comment by Qwithe** [comment]
Seems the issue is still there in version furniture-7.0.0-pre5-1.14.4

**Comment by sumduck** [comment]
> I fixed it by replacing sliding door files in 6.3.0 with files from 5.12.0 version.
> 
> [CFM 6.3.0 - MC 1.12.2 - Sliding Doors Fix.zip](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/3436829/CFM.6.3.0.-.MC.1.12.2.-.Sliding.Doors.Fix.zip)

Wait so how exactly do you do this?
